# configs/nuno_absence.yml
absence_types:
  vacation_96635254: "Ferie"
  leave_96725821: "Permittert (uten lønn)"
  leave_96635259: "Fødselspermisjon"
  other_98194367: "Fleksitid"
  leave_96726627: "Permittert (arbeidsgiverperiode)"
  illness_96728279: "Sykdom barn"
  timeOff_96635255: "Avspasering"
  illness_676657139: "Sykmeldt"
  leave_96635260: "Velferdspermisjon"
  leave_96723478: "Permisjon uten lønn"
  illness_96635256: "Sykdom"
  leave_96724420: "Permisjon med lønn"

absence_rules:
  include_in_capacity_reduction:
    - illness_676657139         # Sykmeldt
    - leave_96635259            # Fødselspermisjon
    - leave_96723478            # Permisjon uten lønn
    - leave_96725821            # Permittert (uten lønn)
    - other_98194367            # Fleksitid
    - timeOff_96635255          # Avspasering
    - vacation_96635254         # Ferie
  exclude_from_capacity_reduction:
    - leave_96726627            # Permittert (arbeidsgiverperiode)
    - illness_96728279          # Sykdom barn
    - leave_96635260            # Velferdspermisjon
    - illness_96635256          # Sykdom
    - leave_96724420            # Permisjon med lønn

billable_target: 0.80